"""Dataset versioning — DVC-compatible snapshots of the labeled corpus.

Every retrain must be reproducible: given a version tag you must be able
to reconstruct exactly which labeled frames, with which annotations, went
into that training run. This module provides that guarantee without
requiring a running DVC server.

Mechanism:
* A ``DatasetVersion`` is a frozen JSON manifest listing every
  ``LabelEntry`` incorporated, the per-class counts, and the SHA-256
  of the JSONL queue file at snapshot time (the hash of the hashes).
* The manifest is written to ``<version_dir>/<tag>.json``.
* A companion ``<tag>.dvc`` stub is written in DVC metafile format so
  the file can be tracked by ``dvc add`` on the GPU box without any
  Python logic there.
* Versions are immutable once written — a tag that exists is never
  overwritten (append-only provenance).

DVC integration notes (for the GPU box operator):
    dvc add data/labels/<tag>.json
    git add data/labels/<tag>.json.dvc data/labels/.gitignore
    git commit -m "dataset: <tag>"
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator

from datalayer.labelstore import LabelEntry, LabelQueue, LabelStatus

log = logging.getLogger("xray.datalayer.versioning")

_MANIFEST_SUFFIX = ".json"
_DVC_STUB_SUFFIX = ".dvc"


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------
@dataclass
class DatasetVersion:
    """Immutable snapshot of the labeled corpus at a point in time."""

    tag: str                            # e.g. "v0.3.1" or "2025-06-15"
    created_at: str                     # ISO-8601 UTC
    label_count: int
    per_class_counts: dict[str, int]
    queue_sha256: str                   # SHA-256 of the JSONL queue file bytes
    entries: list[dict]                 # serialised LabelEntry dicts

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(asdict(self), indent=indent, ensure_ascii=False)

    @classmethod
    def from_json(cls, raw: str) -> "DatasetVersion":
        obj = json.loads(raw)
        return cls(**obj)


# ---------------------------------------------------------------------------
# DVC stub writer
# ---------------------------------------------------------------------------
def _write_dvc_stub(manifest_path: Path, manifest_sha256: str, manifest_bytes: int) -> Path:
    """Write a minimal DVC metafile next to the manifest.

    This is a syntactically valid .dvc file that ``dvc checkout`` can use.
    The GPU box only needs to ``dvc add`` the manifest; this stub makes
    that idempotent across boxes.
    """
    stub_path = manifest_path.with_suffix(_DVC_STUB_SUFFIX)
    content = (
        "# DVC metafile — auto-generated by datalayer.versioning\n"
        "# Do not edit manually.\n"
        "outs:\n"
        f"- md5: {manifest_sha256}\n"
        f"  size: {manifest_bytes}\n"
        f"  path: {manifest_path.name}\n"
    )
    stub_path.write_text(content, encoding="utf-8")
    return stub_path


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------
class VersioningManager:
    """Creates and reads versioned dataset snapshots.

    Writes manifests to ``<version_dir>/``. Manifests are append-only;
    writing a tag that already exists raises ``FileExistsError``.
    """

    def __init__(self, version_dir: str | Path) -> None:
        self._dir = Path(version_dir)
        self._dir.mkdir(parents=True, exist_ok=True)

    def _manifest_path(self, tag: str) -> Path:
        safe_tag = tag.replace("/", "_").replace(" ", "_")
        return self._dir / f"{safe_tag}{_MANIFEST_SUFFIX}"

    # -- snapshot ----------------------------------------------------------
    def create_snapshot(
        self,
        tag: str,
        queue: LabelQueue,
        *,
        status: LabelStatus = LabelStatus.REVIEWED,
    ) -> DatasetVersion:
        """Freeze all entries at ``status`` into a versioned manifest.

        Raises:
            FileExistsError: if the tag already exists.
            ValueError: if there are no entries at the given status.
        """
        out = self._manifest_path(tag)
        if out.exists():
            raise FileExistsError(f"Dataset version {tag!r} already exists at {out}.")

        # Collect entries.
        entries_raw: list[dict] = []
        per_class: dict[str, int] = {}
        with queue.queue_path.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    if obj.get("status") == status.value:
                        entries_raw.append(obj)
                        cat = obj.get("category", "unknown")
                        per_class[cat] = per_class.get(cat, 0) + 1
                except Exception as exc:
                    log.warning("Skipping malformed line during snapshot: %s", exc)

        if not entries_raw:
            raise ValueError(f"No entries with status={status.value!r} found in queue.")

        queue_sha256 = _sha256_file(queue.queue_path)

        version = DatasetVersion(
            tag=tag,
            created_at=datetime.now(timezone.utc).isoformat(),
            label_count=len(entries_raw),
            per_class_counts=per_class,
            queue_sha256=queue_sha256,
            entries=entries_raw,
        )

        manifest_bytes = version.to_json().encode("utf-8")
        manifest_sha256 = hashlib.sha256(manifest_bytes).hexdigest()

        out.write_bytes(manifest_bytes)
        dvc_stub = _write_dvc_stub(out, manifest_sha256, len(manifest_bytes))

        log.info(
            "snapshot tag=%s labels=%d manifest_sha256=%s dvc_stub=%s",
            tag,
            len(entries_raw),
            manifest_sha256[:12],
            dvc_stub.name,
        )
        return version

    # -- read --------------------------------------------------------------
    def load(self, tag: str) -> DatasetVersion:
        path = self._manifest_path(tag)
        if not path.exists():
            raise FileNotFoundError(f"Dataset version {tag!r} not found at {path}.")
        return DatasetVersion.from_json(path.read_text(encoding="utf-8"))

    def list_versions(self) -> list[str]:
        return sorted(
            p.stem for p in self._dir.glob(f"*{_MANIFEST_SUFFIX}")
        )

    def latest(self) -> DatasetVersion | None:
        tags = self.list_versions()
        return self.load(tags[-1]) if tags else None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65_536), b""):
            h.update(chunk)
    return h.hexdigest()


__all__ = [
    "DatasetVersion",
    "VersioningManager",
]
