"""Explicit false-negative test cases — per threat category, per difficulty.

These tests are distinct from the aggregate metric gates in test_detector_metrics.py.
Each test here is a targeted, labelled scenario:

    "When a firearm is clearly visible in the left half of the image,
     the detector must produce at least one FIREARM detection."

This gives failure messages that name exactly which scenario was missed,
accelerating diagnosis.  Each scenario has an associated minimum confidence
threshold — a detection at 0.05 confidence is worse than no detection.

The tests use synthetic images generated by make_synthetic_xray() when no real
image is available (XRAY_TEST_DATASET_PATH not set), or load named crops from
disk when available.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest

from contracts.v1.common import ThreatCategory

REQUIRES_REAL_DATA = pytest.mark.skipif(
    not os.environ.get("XRAY_TEST_DATASET_PATH"),
    reason="XRAY_TEST_DATASET_PATH not set — skipping real-image FN tests",
)

REQUIRES_DETECTOR = pytest.mark.skipif(
    os.environ.get("XRAY_DETECTOR_ENABLED", "false").lower() != "true",
    reason="XRAY_DETECTOR_ENABLED not set — skipping real detector FN tests",
)

# Minimum confidence for a detection to count as a true detection
MIN_CONFIDENCE: float = float(os.environ.get("XRAY_GATE_MIN_CONFIDENCE", "0.30"))


# ---------------------------------------------------------------------------
# Synthetic image generator (used when no real dataset is present)
# ---------------------------------------------------------------------------

def make_synthetic_xray(
    width: int = 512,
    height: int = 384,
    inject_category: ThreatCategory | None = None,
    brightness_level: int = 200,
) -> np.ndarray:
    """Create a minimal synthetic X-ray grayscale image.

    In smoke-test mode (no real detector), this generates a gray image that the
    mock detector will process correctly by category label.
    """
    img = np.full((height, width, 3), 128, dtype=np.uint8)
    if inject_category is not None:
        # Stamp a darker rectangle to simulate a dense object
        x, y, w, h = width // 4, height // 4, width // 4, height // 4
        img[y:y+h, x:x+w] = [40, 40, 40]   # dark region = high-Z material
    return img


# ---------------------------------------------------------------------------
# Mock detector wrapper (identical interface to real detector)
# ---------------------------------------------------------------------------

class _MockDetectorResult:
    """Minimal shim matching detector.serving output interface."""
    def __init__(self, category: ThreatCategory | None, score: float = 0.85):
        self.has_findings = category is not None
        self.detections = []
        if category is not None:
            from tests.fixtures.builders import make_detection
            self.detections = [make_detection(category=category, score=score)]


def _get_detector():
    """Return the real detector if enabled, else a callable mock."""
    if os.environ.get("XRAY_DETECTOR_ENABLED", "false").lower() == "true":
        from detector.serving.composition import DetectorConfig, build_detector
        cfg = DetectorConfig(
            weights=os.environ["XRAY_DETECTOR_WEIGHTS"],
            device=os.environ.get("XRAY_DETECTOR_DEVICE", "cpu"),
            name="xray-detector",
            version=os.environ.get("XRAY_DETECTOR_VERSION", "test"),
        )
        return build_detector(cfg)
    # Mock: always detects whatever category the image was annotated with
    class MockDetector:
        def predict_array(self, img: np.ndarray, *, category_hint=None):
            return _MockDetectorResult(category_hint)
    return MockDetector()


@pytest.fixture(scope="module")
def detector():
    return _get_detector()


def _run(detector, img: np.ndarray, expected_cat: ThreatCategory):
    """Helper: run detector and return (detected: bool, top_score: float)."""
    has_hint = hasattr(detector, "predict_array")
    if has_hint:
        result = detector.predict_array(img, category_hint=expected_cat)
    else:
        # Real detector: no category hint
        result = detector.run_on_array(img)

    matching = [d for d in result.detections if d.category == expected_cat]
    detected = bool(matching)
    top_score = max((d.score for d in matching), default=0.0)
    return detected, top_score


# ---------------------------------------------------------------------------
# Parametrized FN scenario tests
# ---------------------------------------------------------------------------

FN_SCENARIOS = [
    # (category, difficulty, description)
    (ThreatCategory.FIREARM,        "easy",   "handgun, clearly isolated, full view"),
    (ThreatCategory.FIREARM,        "medium", "handgun, partially occluded by clothing"),
    (ThreatCategory.FIREARM,        "hard",   "disassembled firearm components, scattered"),
    (ThreatCategory.EXPLOSIVE,      "easy",   "block explosive, clear outline"),
    (ThreatCategory.EXPLOSIVE,      "medium", "pipe bomb shape, embedded in luggage"),
    (ThreatCategory.NARCOTICS,      "easy",   "brick-shaped dense organic, isolated"),
    (ThreatCategory.NARCOTICS,      "medium", "compressed tablets, small package"),
    (ThreatCategory.BLADED_WEAPON,  "easy",   "kitchen knife, clear profile"),
    (ThreatCategory.BLADED_WEAPON,  "medium", "folding blade, closed, mixed with tools"),
    (ThreatCategory.CURRENCY,       "easy",   "bundled banknotes, clear view"),
    (ThreatCategory.METALLIC_ANOMALY, "medium", "dense metallic block, irregular shape"),
    (ThreatCategory.ORGANIC_ANOMALY, "medium", "compressed organic mass, unusual density"),
]


@pytest.mark.parametrize("category,difficulty,description", FN_SCENARIOS)
def test_detector_does_not_miss_scenario(
    detector,
    category: ThreatCategory,
    difficulty: str,
    description: str,
):
    """The detector must produce a detection for each named FN scenario.

    Failure message names the exact scenario so the ML team knows what to fix.
    """
    # Try to load a real crop if available
    dataset_path = os.environ.get("XRAY_TEST_DATASET_PATH", "")
    img = None
    if dataset_path:
        crop_dir = Path(dataset_path) / "fn_scenarios"
        candidate = crop_dir / f"{category.value}_{difficulty}.png"
        if candidate.exists():
            from PIL import Image
            img = np.array(Image.open(candidate))

    if img is None:
        img = make_synthetic_xray(inject_category=category)

    detected, score = _run(detector, img, category)

    assert detected, (
        f"FALSE NEGATIVE: detector missed '{description}' "
        f"(category={category.value}, difficulty={difficulty}). "
        f"This must be caught before release."
    )
    assert score >= MIN_CONFIDENCE, (
        f"Detection found but confidence {score:.3f} < minimum {MIN_CONFIDENCE:.3f} "
        f"for scenario: '{description}' ({category.value}/{difficulty})."
    )


# ---------------------------------------------------------------------------
# Scenario: scan with multiple co-located threats
# ---------------------------------------------------------------------------

def test_detector_finds_multiple_threats_in_one_scan(detector):
    """When two distinct threat objects are present, both must be detected."""
    img = make_synthetic_xray()

    # In real mode we'd have a multi-threat crop; in mock mode we verify the
    # interface contract: two separate detect calls both succeed.
    for cat in [ThreatCategory.FIREARM, ThreatCategory.BLADED_WEAPON]:
        detected, _ = _run(detector, img, cat)
        assert detected, (
            f"Detector missed {cat.value} in multi-threat scan. "
            "Both threats in a scan must be flagged."
        )


# ---------------------------------------------------------------------------
# Scenario: detector must NOT be fooled by empty scans producing detections
# ---------------------------------------------------------------------------

def test_detector_is_quiet_on_empty_scan(detector):
    """An empty scan (no objects) must not produce false positive detections.

    FP on empty scans is a sign of model over-sensitivity or data contamination.
    """
    empty_img = np.full((384, 512, 3), 200, dtype=np.uint8)  # flat bright background
    if os.environ.get("XRAY_DETECTOR_ENABLED", "false").lower() == "true":
        result = detector.run_on_array(empty_img)
        high_conf_dets = [d for d in result.detections if d.score >= 0.50]
        assert not high_conf_dets, (
            f"Detector produced {len(high_conf_dets)} high-confidence detection(s) "
            "on a blank image. Possible background false-positive issue."
        )


# ---------------------------------------------------------------------------
# Scenario: confidence below threshold produces a detection but flags review
# ---------------------------------------------------------------------------

def test_low_confidence_detection_not_suppressed(detector):
    """A detection with score 0.31 (just above 0.30 gate) must still be emitted.

    The detector must NOT silently suppress borderline detections; those are
    surfaced to the operator for manual review.  Suppression is a policy decision
    made by the API threshold cache, not the detector model.
    """
    # This is primarily a contract test — the detector output format must include
    # all detections above the model's own threshold; filtering happens upstream.
    # We validate the contract structure here.
    from tests.fixtures.builders import make_detection_result, make_detection
    det = make_detection(score=0.31, category=ThreatCategory.FIREARM)
    result = make_detection_result(detections=[det])

    assert result.has_findings is True
    assert len(result.detections) == 1
    assert result.detections[0].score == pytest.approx(0.31)
